site_name: Ava's notes

nav:
  - Home: index.md
  - 'idea':
    - '快捷键': 'idea/快捷键.md'
    - '编辑': 'idea/编辑.md'
    - '跳转切换': 'idea/跳转切换.md'
  - 'git':
    - '添加ssh key': 'git/add-ssh-key.md'
    - '常用命令': 'git/git常用命令.md'
    - 'github超时': 'git/github超时.md'
    - '自用git常用命令': 'git/my-git-commands.md'
  - 'windows':
    - '必备软件': 'windows/必备应用.md'
    - 'win快捷键': 'windows/win快捷键.md'
    - '禁用firefox更新': 'windows/禁用firefox更新.md'
    - '禁用Firefox3地址栏的下拉菜单': 'windows/禁用Firefox3地址栏的下拉菜单.md'
    - 'sublime之Package Control': 'windows/sublime之Package Control.md'
    - 'pandoc使用技巧': 'windows/pandoc使用技巧.md'
    - 'cmder': 'windows/cmder-issue.md'
    - 'markdown中公式编辑教程': 'windows/markdown中公式编辑教程.md'
  - 'linux':
    - '分区方案': 'linux/partition-scheme.md'
    - '安装arch': 'linux/install-arch.md'
    - 'Linux下有用的命令行快捷键': 'linux/linux-shortcut-key.md'
    - '磁盘的挂载、分区、格式化与检验': 'linux/disk-mount-partition-format.md'
    - '查看磁盘与目录的容量': 'linux/watch-disk-directory-capacity.md'
    - '添加环境变量': 'linux/add-path.md'
    - '新增用户': 'linux/add-user.md'
    - 'vim': 'linux/vim.md'
    - 'tar': 'linux/tar.md'
    - 'tee': 'linux/tee.md'
    - 'iptables': 'linux/iptables.md'
    - 'firewalld': 'linux/firewalld.md'
    - '进程管理': 'linux/process-manage.md'
    - '查看进程': 'linux/watch-process.md'
    - '配置ssh登录': 'linux/configure-ssh.md'
    - '升级内核': 'linux/update-kernel.md'
    - '使用make进行宏编译': 'linux/make-translation.md'
    - '设置yum源优先级': 'linux/change-yum-priority.md'
    - '系统资源观察': 'linux/watch-system-source.md'
    - '修改语系': 'linux/chang-language.md'
    - '分割和合并文件': 'linux/split-merge-file.md'
    - '生成本地仓库': 'linux/generate-local-repo.md'
    - '任务管理': 'linux/job-control.md'
    - '定时任务': 'linux/timing-task.md'
    - 'tarball管理': 'linux/tarball-manager.md'
    - '备份策略': 'linux/backup-strategy.md'
    - '关闭网络服务': 'linux/stop-service.md'
    - '修改进程优先级': 'linux/change-process-priority.md'
    - 'ansible入门': 'linux/ansible.md'
    - 'nginx': 'linux/nginx.md'
    - '安装docker': 'linux/install-docker.md'
  - 'docker':
    - '安装docker': 'docker/安装docker.md'
    - 'docker常用指令': 'docker/docker常用指令.md'
    - '导入导出镜像': 'docker/导入导出镜像.md'
    - 'debian容器中运行本地仓库': 'docker/debian容器中运行本地仓库.md'
    - 'Containerd常见操作': 'docker/Containerd常见操作.md'
    - '启动各种容器':
      - '启动redis': 'docker/启动各种容器/启动redis.md'
      - '启动mysql': 'docker/启动各种容器/启动mysql.md'
      - '启动kafka': 'docker/启动各种容器/启动kafka.md'
      - '启动rabbitmq': 'docker/启动各种容器/启动rabbitmq.md'
      - '启动sonarqube': 'docker/启动各种容器/启动sonarqube.md'
  - 'springboot':
    - 'mybatis-plus自动生成代码': 'springboot/mybatis-plus自动生成代码.md'
    - 'json序列化':
      - 'dto序列化': 'springboot/json序列化/前端序列化.md'
    - 'Long转String': 'springboot/Long转String.md'
    - '复制bean': 'springboot/复制bean.md'
    - '多数据源配置': 'springboot/多数据源配置.md'
    - '入参校验': 'springboot/入参有效性校验.md'
    - '枚举类': 'springboot/枚举类.md'
    - 'aop':
      - '限制访问频率': 'springboot/springboot使用AOP限制访问频率.md'
    - '使用jms发送邮件': 'springboot/springboot使用jms发送邮件.md'
    - '使用redis': 'springboot/springboot使用redis.md'
    - '函数式编程':
      - '分组求最值': 'springboot/stream求组内最大值.md'
    - '死锁样例': 'springboot/死锁.md'
  - 'kubernetes':
    - '准备工作':
      - '设置免密登录': 'kubernetes/1.免密登录.md'
      - '时间同步': 'kubernetes/2.时间同步.md'
      - '内核参数优化': 'kubernetes/3.内核参数优化.md'
      - '修改sysctl配置': 'kubernetes/3.修改sysctl配置.md'
      - '关闭相关服务': 'kubernetes/4.关闭相关服务.md'
      - '提供底层存储': 'kubernetes/5.提供底层存储.md'
      - '为ceph提供provisioner': 'kubernetes/6.为ceph提供provisioner.md'
      - '安装helm': 'kubernetes/7.安装helm.md'
      - 'ingress':
        - 'ingress的作用及部署': 'kubernetes/ingress.md'
        - 'nginx-ingress补充': 'kubernetes/nginx-ingress补充.md'
        - '部署ingress-controller': 'kubernetes/8.部署ingress-controller.md'
      - '部署kubernetes-dashboard': 'kubernetes/9.部署kubernetes-dashboard.md'
      - '部署harbor': 'kubernetes/10.部署harbor.md'
      - '使用证书': 'kubernetes/11.使用证书.md'
    - '部署应用':
      - '自动扩容': 'kubernetes/12.自动扩容.md'
      - '部署mysql': 'kubernetes/13.部署mysql.md'
      - '部署jenkins':
        - 'helm安装jenkins': 'kubernetes/14.部署jenkins.md'
        - '为jenkins添加静态agent节点': 'kubernetes/14-1.为jenkins添加静态agent节点.md'
        - 'jenkinsfile模板': 'kubernetes/14-2.jenkinsfile模板.md'
      - '部署redis': 'kubernetes/15.部署redis.md'
      - '部署kafka': 'kubernetes/16.部署kafka.md'
      - '部署rabbitmq': 'kubernetes/17.部署rabbitmq.md'
      - '部署consul': 'kubernetes/18.部署consul.md'
      - '部署kube-prometheus-stack': 'kubernetes/19.部署kube-prometheus-stack.md'
      - 'EFK收集日志': 'kubernetes/20.EFK收集日志.md'
      - '部署gitlab': 'kubernetes/21.部署gitlab.md'
    - 'helm卸载时不删除pvc': 'kubernetes/helm卸载时不删除pvc.md'
    - '自动补全': 'kubernetes/自动补全.md'
    - '以root权限启动容器': 'kubernetes/以root权限启动容器.md'
    - '修改容器时间': 'kubernetes/修改容器时间.md'
    - '通过endpoints代理集群外服务': 'kubernetes/通过endpoints代理集群外服务.md'
    - '固定pod的ip': 'kubernetes/固定pod的ip.md'
    - 'Role和ClusterRole': 'kubernetes/Role-ClusterRole.md'
    - 'RoleBinding和ClusterRoleBinding': 'kubernetes/RoleBinding-ClusterRoleBinding.md'
    - 'nfs提供storageclass':
      - 'docker部署nfs': 'kubernetes/nfs提供storageclass/01.docker部署nfs.md'
      - 'helm部署nfs作为storageclass': 'kubernetes/nfs提供storageclass/02.使用nfs作为storageclass.md'
    - 'kube-prometheus-stack':
      - 'alermanager配置email': 'kubernetes/kube-prometheus-stack/alermanager-email.md'
      - 'alermanager路由配置详解': 'kubernetes/kube-prometheus-stack/alertmanager路由配置详解.md'
    - 'k8s最佳实践':
      - '如何构建尽可能小的容器镜像': 'kubernetes/k8s最佳实践/01.如何构建尽可能小的容器镜像.md'
      - '如何使用命名空间管理kubernetes资源': 'kubernetes/k8s最佳实践/02.如何使用命名空间管理kubernetes资源.md'
      - '健康检查': 'kubernetes/k8s最佳实践/03.健康检查.md'
      - '资源请求和限制': 'kubernetes/k8s最佳实践/04.资源请求和限制.md'
      - '如何优雅地终止': 'kubernetes/k8s最佳实践/05.如何优雅地终止.md'
      - 'Kubernetes的内置服务发现机制运行集群外部服务': 'kubernetes/k8s最佳实践/06.Kubernetes的内置服务发现机制运行集群外部服务.md'
      - '零停机更新kubernetes集群': 'kubernetes/k8s最佳实践/07.零停机更新kubernetes集群.md'
  - 'ceph':
    - '生成本地仓库安装ceph': 'ceph/0.生成本地仓库安装ceph.md'
    - '配置客户端': 'ceph/1.配置客户端.md'
    - '创建ceph块设备': 'ceph/2.创建ceph块设备.md'
    - '映射ceph块设备': 'ceph/3.映射ceph块设备.md'
    - '调整ceph RBD大小': 'ceph/4.调整ceph RBD大小.md'
    - '使用快照': 'ceph/5.使用快照.md'
    - 'docker-compose部署ceph':
      - '部署ceph': 'ceph/docker-compose部署ceph/1-1.部署文档.md'
      - '为k8s提供storageClass':
        - 'kube-controller-manager镜像中添加rbd': 'ceph/docker-compose部署ceph/2.0.构建带rbd的controller-manager.md'
        - '使用provisioner提供rbd': 'ceph/docker-compose部署ceph/2.1.k8s使用provisioner提供rbd.md'
        - 'k8s使用storageClass': 'ceph/docker-compose部署ceph/2.2.ceph-rbd-sc.md'
  - 'latex':
    - '配置sublime+latex': 'latex/sublime+latex.md'
    - 'TeX小结': 'latex/TeX小结.md'
    - '代码环境': 'latex/代码环境.md'
    - '定理环境': 'latex/定理环境.md'
  - '其他':
    - 'mysql定时备份': 'other/mysql备份.md'
theme:
  name: 'material'
  # name: 'mkdocs'
  palette:
    primary: "grey"
    accent: "deep orange"
  font:
    code: Roboto Mono
  # locale: zh_CN

plugins:
  - search:
      lang: en

# 代码块语法高亮
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # latex插件
  - pymdownx.arithmatex:
      generic: true

# 代码块语法高亮
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  # latex js配置
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
  # - quote_block.css
